services:
  - type: web
    name: mila
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 18.15.0
      - key: TENOR_API_KEY
        sync: false
      - key: NODE_ENV
        value: production
    plan: free
    healthCheckPath: /health
    healthCheckTimeout: 100
    autoDeploy: true
